### ISSUE TITLE
authorizing requires read and write access to my repos

### ISSUE THREAD

**Issue by cgwalters** [coreos/coreos-ci#12]
Trying to log into https://jenkins-coreos-ci.apps.ci.centos.org it requests oauth scope for read and *write* access to my personal repositories.  This seems unnecessary.

**Comment by cgwalters** [comment]
It also seems to be owned by jlebon - is that @jlebon your personal account?  I think we want this to be owned by the coreos org?

**Comment by jlebon** [comment]
https://github.com/coreos/coreos-ci/pull/13

> It also seems to be owned by jlebon - is that @jlebon your personal account? I think we want this to be owned by the coreos org?

Yes, we do, see [HACKING.md](https://github.com/coreos/coreos-ci/blob/master/HACKING.md):

> Create the GitHub OAuth secret (these creds currently live in jlebon's "CoreOS CI" GitHub OAuth App settings, which he will soon transfer to the coreos/ org).

;)  Just didn't want to do this prematurely while we were still evaluating the concept. I think it makes sense to do now though.
