### ISSUE TITLE
fork: retry: Resource temporarily unavailable

### ISSUE THREAD

**Issue by cgwalters** [coreos/coreos-ci#23]
We're seeing e.g. `./libtool: fork: retry: Resource temporarily unavailable` in the rpm-ostree CI jobs.

One thing I notice is RPM's `%{make_build}` macro is detecting 40 CPUs: `/usr/bin/make -O -j40`.  We might even be hitting PID limits, or perhaps per-user?

Googling around a bit I found https://github.com/openSUSE/obs-build/issues/425 and looking at the rpm macros, it does seem likely that we could inject `-D _smp_ncpus_max=8` or so?

**Comment by cgwalters** [comment]
But I still think we have the larger "CPUs versus Kubernetes" issue that came up in the code in https://github.com/coreos/coreos-assembler/pull/1287

**Comment by cgwalters** [comment]
Thinking about this actually, in rpm-ostree in particular our tests do this:
`JOBS=${JOBS:-$(ncpus)}` and then actually each rpm-ostree compose process will e.g. parallelize RPM imports with threads (up to 40...).  If we have several of these jobs running at once that can add up.

Ah but in rpm-ostree `ncpus` does do the "detect kubernetes" dance.  Hmm...let's export that in cosa and have it in the buildroot by default?  

Actually related to this, one really nice thing `cargo` does is [interact with a make jobserver](https://github.com/rust-lang/cargo/pull/4110/commits/cbf25a9b0ae5ac6f5b6da96e645b7fa6a75dc245) - perhaps our cosa jobs should export a jobserver by default.

**Comment by jlebon** [comment]
Yeah, sadly right now we're responsible for bridging build tools' view of resources available and the Kubernetes world. I think most of our workloads do have this bridging now, but it looks like RPM building escaped through. Would be nice if in the future, e.g. `make` just knows how many jobs to run in parallel based on cgroups allocation. (Or maybe there should be a namespace feature which allows modifying how many CPUs processes can see?)

The `_smp_ncpus_max` macro bit sounds promising. I can play around with that.
