### ISSUE TITLE
Simplify the Bodhi trigger (when Bodhi 8.0 hits production)

### ISSUE THREAD

**Issue by AdamWill** [coreos/coreos-ci#53]
In https://github.com/fedora-infra/bodhi/pull/5538 , I changed Bodhi to always publish UpdateReadyForTesting (that's `bodhi.update.status.testing.koji-build-group.build.complete`) in the scenarios when we want to trigger tests:

1. When an update is created
2. When an update is edited and its builds change
3. When someone hits the Re-Trigger Tests button

This should mean we can vastly simplify https://github.com/coreos/coreos-ci/blob/main/jobs/bodhi-trigger.Jenkinsfile - it should no longer need to worry about consuming `update.request.testing` or `update.edit` messages, or distinguishing between retrigger and non-retrigger cases of `update.status.testing.koji-build-group.build.complete`. It can just fire tests any time it sees that message, and that should cover everything.

8.0 is deployed in staging now, so you can mess around at https://bodhi.stg.fedoraproject.org/ , creating and editing updates and hitting the Re-Trigger Tests button, and watch https://apps.stg.fedoraproject.org/datagrepper/raw?category=bodhi&delta=172800 to see the results. It seems to be working as intended in my testing.

**Comment by AdamWill** [comment]
note you really will get the message *the moment an update is created*, at which point its builds will not be in updates-testing and will not yet be signed (they should get signed shortly afterwards). I don't believe this should be a problem, but worth noting.

**Comment by jlebon** [comment]
Awesome, thanks @AdamWill for the heads up!

**Comment by jlebon** [comment]
@AdamWill Do you know when v8.0 is planned to enter production?

**Comment by AdamWill** [comment]
@nirik and @mattiaverga have kicked it around a couple of times on Matrix that I saw, so I think not too long, but probably Kevin is trying to find a somewhat fire-free day to do it on. It's been quite fiery lately.

**Comment by nirik** [comment]
Yeah, we are hoping this week (so, tomorrow perhaps?)

**Comment by nirik** [comment]
Sure, just ping me on matrix when you have time. I should be around this weekend too...

**Comment by jlebon** [comment]
PR in https://github.com/coreos/coreos-ci/pull/56 for when we're ready.

One thing though I was sad to see though was the removal of `.artifacts.builds[].component`. Commented about that in https://github.com/fedora-infra/bodhi/pull/5538#issuecomment-1922112048.

**Comment by jlebon** [comment]
To be sure, this unified trigger should work fine for both dev (rawhide/branched) and stable releases, right? (Previously: https://github.com/coreos/coreos-ci/pull/49#issuecomment-1771882189).

**Comment by AdamWill** [comment]
Yes.
