### ISSUE TITLE
Failure notifications are not being posted to Matrix

### ISSUE THREAD

**Issue by jlebon** [coreos/coreos-ci#65]
E.g. https://jenkins-coreos-ci.apps.ocp.fedoraproject.org/job/bodhi-trigger/619/console:

> 13:25:17 ERROR: Could not find credentials entry with ID 'matrix-bot-webhook-token'

**Comment by jbtrystram** [comment]
100% me going too fast : it worked on the test CI so I thought "all good!" and merged. I never created the secret in the correct oc project ... Fixed

**Comment by jbtrystram** [comment]
This still fails with 
```
17:47:12  Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: d5469bd5-c734-459d-8502-8ff7198756e5
17:47:12  groovy.lang.MissingPropertyException: No such property: MATRIX_WEBHOOK_URL for class: groovy.lang.Binding
17:47:12  	at groovy.lang.Binding.getVariable(Binding.java:63)
```

I don't understand why since it was working fine with https://github.com/coreos/fedora-coreos-pipeline/pull/996#issuecomment-2133395433

**Comment by jlebon** [comment]
> This still fails with
> 
> ```
> 17:47:12  Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: d5469bd5-c734-459d-8502-8ff7198756e5
> 17:47:12  groovy.lang.MissingPropertyException: No such property: MATRIX_WEBHOOK_URL for class: groovy.lang.Binding
> 17:47:12  	at groovy.lang.Binding.getVariable(Binding.java:63)
> ```
> 
> I don't understand why since it was working fine with [coreos/fedora-coreos-pipeline#996 (comment)](https://github.com/coreos/fedora-coreos-pipeline/pull/996#issuecomment-2133395433)

Sorry, missed this. I think https://github.com/coreos/fedora-coreos-pipeline/pull/1001 should fix it.

**Comment by jlebon** [comment]
This should be fixed now. Optimistically closing.
