### ISSUE TITLE
Bodhi-trigger notifications formatting does not work

### ISSUE THREAD

**Issue by jbtrystram** [coreos/coreos-ci#67]
The emojis and markdown formatting is not applied in the matrix notifications : 
```
:fire: [:ocean:](https://jenkins-coreos-ci.apps.ocp.fedoraproject.org//blue/organizations/jenkins/test-override/detail/test-override/693) systemd-256-1.fc41 - FAILED 
```

Also, it would be nice to have a link to the bodhi update page in the message

**Comment by jlebon** [comment]
It might work to put literal valid Unicode emojis instead. E.g. 🔥 for fire and 🌊 for ocean.

**Comment by jbtrystram** [comment]
According to https://github.com/fedora-infra/maubot-webhook we need to update the webhook to use "formatting: markdown"
